name: Deploy Backend to VPS

on:
  push:
    branches: [ "main" ] # Запускать при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          # password: ${{ secrets.PASSWORD }}
          # Если используете ключ, раскомментируйте строку ниже и закомментируйте password
          key: ${{ secrets.SSH_KEY }}
          source: "main.py,models.py,admin.py,database.py,requirements.txt,templates/"
          target: "/root/profisfera-backend" # ЗАМЕНИТЕ на реальный путь до папки на сервере!
          overwrite: true

      - name: Restart Systemd Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          # password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/profisfera-backend
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart profisfera